kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipelines-persistence-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi