# Use tensorflow-1.14.0 as a base image, allowing the user to
# speficy if they want GPU support, by setting IMAGE_TYPE to "gpu".
FROM gcr.io/arrikto-public/tensorflow-1.14.0-notebook-cpu:kubecon-workshop

USER root

RUN echo 'alias grep="grep --color=auto' >> /etc/bash.bashrc && \
    echo 'alias ls="ls --color=auto' >> /etc/bash.bashrc

# Install latest KFP SDK
RUN pip3 install --upgrade pip && \
    pip3 install https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz --upgrade

# Install Kale from KALE_BRANCH (defaults to "master")
ARG KALE_BRANCH="master"
WORKDIR /
RUN rm -rf /kale && \
    git clone -b ${KALE_BRANCH} https://github.com/kubeflow-kale/kale && \
    cd /kale && \
    python setup.py install && \
    cd / && \
    rm -rf /kale

# Install JupyterLab Extension from KALE_EXT_BRANCH (defaults to "master")
ARG KALE_EXT_BRANCH="master"
WORKDIR /
RUN rm -rf /jupyterlab-kubeflow-kale && \
    git clone -b ${KALE_EXT_BRANCH} https://github.com/kubeflow-kale/jupyterlab-kubeflow-kale && \
    cd /jupyterlab-kubeflow-kale && \
    jlpm install && \
    jlpm run build && \
    jupyter labextension install . && \
    cd / && \
    rm -rf /jupyterlab-kubeflow-kale

RUN pip3 install jupyterlab==1.1.4 --upgrade && \
    jupyter lab build --dev-build=False

RUN echo "jovyan ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/jovyan
WORKDIR /home/jovyan
USER jovyan

CMD ["sh", "-c", "jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --LabApp.token='' --LabApp.password='' --LabApp.allow_origin='*' --LabApp.base_url=${NB_PREFIX}"]
