name: Check PR Title

on:
  pull_request_target:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            docs
            fix
            feat
            revert

          scopes: |
            frontend
            backend
            ci
            docs
            deps
            examples
            test
          requireScope: false
          ignoreLabels: |
            do-not-merge/work-in-progress
            dependencies
            area/release
